app = 'tangled-ascii'
primary_region = 'sea'

[build]
  dockerfile = './examples/tangled_ascii/Dockerfile'

[env]
  BFF_PORT = '8080'
  BFF_PUBLIC_URL = 'https://tangled-ascii.fly.dev'
  BFF_ROOT_DIR = './examples/tangled_ascii/'
  BFF_LEXICON_DIR = './examples/tangled_ascii/__generated__'
  BFF_DATABASE_URL = '/mnt/sqlite/production.sqlite'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source="sqlite"
  destination="/mnt/sqlite"